<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <AssemblyName>MacroTool</AssemblyName>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MacroTool.Domain\MacroTool.Domain.csproj" />
    <ProjectReference Include="..\MacroTool.Application\MacroTool.Application.csproj" />
    <ProjectReference Include="..\MacroTool.Infrastructure\MacroTool.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MacroTool.Tests" />
  </ItemGroup>
</Project>